### ISSUE TITLE
Gather positions from all Governors and 2018 candidates

### ISSUE THREAD

**Issue by developdaly** [developdaly/guncontrolpositions.com#4]
*Purpose*: To document the Governor's and all 2018 candidates' positions on gun control.

*Methods*:
- When applicable, copy the individual's position straight from their candidate website and cite it as your source.
- Reach out to the individuals via Twitter, Facebook, or email asking, "Would you be willing to provide your position on gun control for guncontrolposition.com?"
- Find public statements from news sources.

Always cite your sources.

**Comment by kaseydaly** [comment]
Larry Kilgorehttps://voterguide.dallasnews.com/2018-primary/races/17/#candidates=candidate-36

**Comment by kaseydaly** [comment]
https://voterguide.dallasnews.com/2018-primary/races/17/#candidates=candidate-36
Larry Secede Kilgore
What changes, if any, should be made to the state’s gun laws?
Eliminate permits and background checks.
ARE YOU SERIOUS???????
